config/routes.rb
NclarkWindows::Application.routes.draw do



  devise_for :businesses, controllers: { registrations: 'businesses/registrations' }

  resources :businesses, only: [:update]
  get 'businesses', to: 'pages#home'

  resources :default_customer_details, except: [:index, :show] do
    collection do
      put :update_ordering, format: :json
    end

    member do
      get :toggle_visible_in_work_list, format: :js
    end
  end

  resources :customer_detail_categories, except: [:index, :show] do
    collection do
      put :update_ordering, format: :json
    end
  end

  resources :areas

  resources :customers do
    resources :risks_assessments do
      member do
        put 'check_assessment', to: 'risks_assessments#check_assessment', as: :check_risks_assessment
      end
    end
    resources :customer_notes, only: [:create, :destroy], format: :js
    resources :attachments, only: [:create, :destroy]
    resources :payments, except: :show

    member do
      post :create_job_for_current_week, format: :js
      get :activate
      get :deactivate
    end

    collection do
      get :clear_quick_search_params
    end
  end

  resources :jobs, except: [:index] do
    resources :job_notes, only: [:create, :destroy], format: :js

    member do
      get :mark_as_risk_checked, format: :js
      get :mark_as_completed, format: :js
      get :unmark_as_completed, format: :js
      put :mark_as_paid, format: :js
      put :update_notes, format: :js
      put :update_price, format: :json
      put :update_invoice_number, format: :json
      get :quick_new
      post :quick_create
    end
  end

  resources :work_list_categories, except: [:index, :show] do
    member do
      patch :update_balance_date_from
    end
  end

  resources :work_lists, only: [:show] do
    resources :work_list_notes, only: [:create, :destroy], format: :js

    collection do
      get :view, format: :js
    end

    member do
      put :update_tag, format: :json
      put :move_jobs, format: :json
      get :mark_as_completed
      get :mark_as_incompleted
      post :customer_search, format: :js
      get :add_job_for_customer, format: :js
      patch :update_target
      put :update_job_ordering, format: :json
      get :reset_job_ordering
      get :get_simple_show, format: :js
    end
  end

  resources :weeks, only: [:index, :show, :edit, :update] do
    collection do
      get :generate_cycle
    end

    member do
      get :work_lists
      patch :pull_work
      patch :push_work
    end
  end

  resources :users, except: [:show] do
    collection do
      get :sign_in
      post :sign_in, to: "users#sign_in_submit"
      get :sign_out_user
    end
  end

  resources :bookmarks, only: [:create], format: :json do
    collection do
      delete :destroy
    end
  end

  resources :finances, only: [:index, :show] do
    collection do
      get :weeks
      post :export
      get :get_export_status, format: :json
    end
  end

  resources :targets, only: [:index, :show]
  resources :expenses

  resources :customer_search_queries, only: [] do
    collection do
      post :search, format: :json
      get :get_search_status, format: :json
      delete :clear_search
      delete :remove_customer_from_search_results
      post :export
      get :get_export_status, format: :json
    end
  end

  get :work_list_settings, to: 'pages#work_list_settings'
  get :toggle_work_list_payment_method, to: 'businesses#toggle_work_list_payment_method', format: :js

  root to: 'pages#home'
end

app/controllers/finances_controller.rb
class FinancesController < ApplicationController
  before_action :authenticate_business!
  before_action :authenticate_user!
  before_action {check_user_role(['Super_Admin','Admin'])}

  def index
    @total_paid_cents = current_business.payments
                                        .in_date_range(params[:from_date], params[:to_date])
                                        .not_credit
                                        .pluck(:cents, :charge_cents)
                                        .inject(0) { |t, p| t + p[0] + p[1] }
    @total_expenses_cents = current_business.expenses
                                            .in_date_range(params[:from_date], params[:to_date])
                                            .pluck(:cents, :vat_cents)
                                            .inject(0) { |t, p| t + p[0] + p[1] }
  end

  def weeks
    @weeks = current_business.weeks.in_date_range(params[:from_week], params[:to_week]).order('weeks.start_date DESC')
    if params[:invoice_number].present?
      @jobs = current_business.jobs.where('jobs.invoice_number ILIKE ?', "%#{params[:invoice_number]}%")
      get_index_default_customer_details_names
    end

    if @weeks.count.zero?
      render :no_finances
    end
  end

  def show
    @week = current_business.weeks.find(params[:id])
    @title = "Finances for week starting #{@week.start_date.to_s(:long)}"
    get_index_default_customer_details_names
  end

  def export
    
    finance_export = current_user.finance_exports.build(terms: params[:export])
    if finance_export.save
      finance_export.delay.perform_export!
    else
      flash[:error] = "Export could not be started (#{finance_export.errors.full_messages.join('; ')})"
    end
    redirect_to request.referrer.present? ? request.referrer : finances_path
  end

  def get_export_status
    if current_user.finance_exports.count > 0
      pending = current_user.has_finances_export_pending?
      render json: {
        status: pending ? 'pending' : 'complete',
        url: pending ? nil : current_user.completed_finance_export.xlsx_file.url
      }
    else
      render json: {
        status: 'none',
        url: nil
      }
    end
  end

private
  def get_index_default_customer_details_names
    @index_default_customer_details_names = current_business.index_default_customer_details.pluck(:name)
  end

end

app/views/finances/_header.html.haml
- unless @title.present?
  %h2 Finances
.nav.nav-tabs
  %li{class: controller_name == "finances" && action_name == "index" && "active"}
    = link_to "Overview", finances_path
  %li{class: controller_name == "finances" && (action_name == "weeks" || action_name == "show") && "active"}
    = link_to "Weeks", weeks_finances_path
  %li{class: controller_name == "targets" && "active"}
    = link_to "Targets", targets_path
  %li{class: controller_name == "expenses" && "active"}
    = link_to "Expenses", expenses_path

app/views/finances/_index_row_titles.html.haml
- hide_edge_columns ||= false
%tr
  %th{width: 150}
    - if hide_edge_columns
      &nbsp;
    - else
      Week starting
  %th Jobs
  %th Total value
  %th Value of completed
  %th Value of completed and paid
  %th Amount outstanding of completed
  %th Amount paid this week
  %th
    - if hide_edge_columns
      &nbsp;
    - else
      Amount paid - Value of completed

app/views/finances/_jobs_table.html.haml
- default_vat_rate = current_business.default_vat_rate
- payment_methods_options = Payment::PAYMENT_METHODS.map { |pm| [pm.titleize, pm] } + [['None', nil]]
%table.table.table-bordered.finance-unpaid-jobs
  %thead
    %th &nbsp;
    %th Invoice No.
    - @index_default_customer_details_names.each do |name|
      %th= name
    %th Job price inc VAT
    %th Total outstanding
    %th &nbsp;
  %tbody
    = jobs.find_each do |job|
      - job.customer.tap do |customer|
        %tr.clickable-row{id: "job-#{job.id}", data: {job_id: job.id, resource: 'customers', id: customer.id}}
          - color_added = false
          %td.clickable{style: "background-color: ##{customer.area_color_cache}"}
            &nbsp;
          %td.clickable
            = job.invoice_number
          - index_detail_values = customer.index_detail_values_from_cache(@index_default_customer_details_names)
          - @index_default_customer_details_names.count.times do |i|
            %td.clickable{style: !color_added && customer.color.present? ? "background-color:##{customer.color}" : ''}
              - color_added = true
              = index_detail_values[i]
          %td.clickable
            = job.price_including_vat.format
          %td.clickable.customer-outstanding-money{class: customer.owing? && 'owing'}
            = customer.outstanding_money.format
          %td.job-paid
            - if job.paid?
              = job.total_payment_amount.format
              \-
              = job.total_payment_method.titleize
            - else
              = link_to "Mark as paid", new_customer_payment_path(job.customer, job_id: job.id, redirect_to_finances: (@week || job.week).id), class: "btn btn-small"
              -# = link_to "Mark as paid", '#', class: "mark-as-paid btn btn-small"
              -# .modal.job-paid-form.hide
              -#   .modal-body
              -#     = form_for job, url: mark_as_paid_job_path(job), method: :put, remote: true do |f|
              -#       %div
              -#         = label_tag 'job[payment_method]', 'Payment method'
              -#         = select_tag 'job[payment_method]', options_for_select(payment_methods_options)
              -#       %div
              -#         = label_tag 'job[payment_amount]', "Amount paid"
              -#         = text_field_tag 'job[payment_amount]', customer.outstanding_money
              -#       %div
              -#         = f.label :invoice_number
              -#         = f.text_field :invoice_number
              -#       %br
              -#       = f.submit "Mark as paid", class: 'btn btn-small'
              -#       = image_tag "ajax-loader.gif", class: "hide ajax-loader"

app/views/finances/index.html.haml
= render 'finances/header'

#date-range-select
  = form_tag finances_path, method: :get do
    = label_tag :from_date
    = date_field_tag :from_date, params[:from_date]
    = label_tag :to_date
    = date_field_tag :to_date, params[:to_date]
    = submit_tag 'Go', class: 'btn'

%table.table.table-bordered.table-vertical
  %tbody
    %tr
      %th Income
      %td= Money.new(@total_paid_cents, 'GBP').format
    %tr
      %th Expenses
      %td= Money.new(@total_expenses_cents, 'GBP').format
    %tr
      %th Profit
      %td= Money.new(@total_paid_cents - @total_expenses_cents, 'GBP').format

#download-report-link{class: current_user.has_finances_export_pending? ? 'hide' : ''}
  #download-report-xlsx-link
    - if current_user.completed_finance_export.present?
      = link_to current_user.completed_finance_export.xlsx_file.url do
        Download XLSX file (generated #{current_user.completed_finance_export.export_finished_at.strftime("%d %b %Y %H:%M")})
  = link_to "Generate report", '#export-finances-modal', data: {toggle: 'modal'}, class: 'btn'
#download-report-pending{class: current_user.has_finances_export_pending? ? '' : 'hide'}
  = image_tag "ajax-loader.gif"
#export-finances-modal.modal.hide{style: 'width: 600px; margin-left: -300px'}
  .modal-body
    = form_tag export_finances_path, method: :post do
      %div
        = label_tag :export_from_date
        = date_field_tag "export[from_date]", params[:from_date]
        = label_tag :export_to_date
        = date_field_tag "export[to_date]", params[:to_date]
      %div
        %strong Payment customer fields to export
        - current_business.customer_detail_categories.each_slice(3) do |category_slice|
          .row
            - category_slice.each do |category|
              .span2
                %strong= category.name
                - category.default_customer_details.each do |detail|
                  = label_tag "export[customer_details][#{detail.name}]", class: 'checkbox' do
                    = detail.name
                    = check_box_tag "export[customer_details][#{detail.name}]"
      %div
        = submit_tag 'Generate', class: 'btn'

:javascript
  $(function() {
    $('#date-range-select form input').on('change', function() {
      var dateRangeForm = $('#date-range-select form');
      var exportForm = $('#export-finances-modal form');
      exportForm.find('#export_from_date').val(dateRangeForm.find('#from_date').val());
      exportForm.find('#export_to_date').val(dateRangeForm.find('#to_date').val());
    });

    if ($('#download-report-pending').is(':visible')) {
      var checkExportStatus = function() {
        $.ajax({
          url: '/finances/get_export_status',
          dataType: 'JSON'
        }).done(function(data) {
          if (data.status == 'complete') {
            $('#download-report-pending').hide();
            $('#download-report-link').show();
            $('#download-report-xlsx-link').html('<a href="' + data.url + '">Download XLSX file</a>');
          } else if (data.status == 'none') {
            $('#download-report-pending').hide();
            $('#download-report-link').show();
          } else {
            setTimeout(checkExportStatus, 1000);
          }
        });
      };
      checkExportStatus();
    }
  });

app/views/finances/no_finances.html.haml
%h2 No finances information to show

app/views/finances/show.html.haml
= render 'finances/header'

= link_to "View week", @week, class: 'btn'

- assigned_jobs_count = 0
%table.table.table-bordered
  %thead
    %tr
      %th Day
      %th Jobs
      %th Total value
      %th Value of completed
      %th Value of completed and paid
      %th Amount outstanding of completed
      %th Amount paid
      %th Amount paid - Value of completed
  %tbody
    - short_days_of_week.each_with_index do |day, day_index|
      - work_lists = @week.work_lists.select { |wl| wl.day == day_index }
      - jobs_count = work_lists.inject(0) { |total, work_list| total + work_list.job_counter_cache }
      - assigned_jobs_count += jobs_count
      %tr
        %td= day
        %td= jobs_count
        %td= @week.value_for_day(day_index).format
        %td= @week.completed_value_for_day(day_index).format
        %td= @week.paid_value_for_day(day_index).format
        %td= @week.outstanding_value_for_day(day_index).format
        %td= (amount_paid = current_business.amount_paid_on_date(@week.start_date + day_index.days)).format
        %td= (amount_paid - @week.completed_value_for_day(day_index)).format

- if assigned_jobs_count < @week.jobs.count
  %h4
    Unassigned jobs: #{@week.jobs.count - assigned_jobs_count}

- if @week.jobs.completed.not_paid.count > 0
  %h4 Unpaid jobs
  = render 'finances/jobs_table', jobs: @week.jobs.unlinked.completed.not_paid.includes(:payments, :customer)

app/views/finances/weeks.html.haml
= render 'finances/header'

= form_tag weeks_finances_path, method: :get do
  = label_tag :invoice_number, 'Search by invoice number'
  = text_field_tag :invoice_number, params[:invoice_number]
  = submit_tag 'Search', class: 'btn'
- if @jobs
  - if @jobs.count.zero?
    No jobs found for invoice number
  - else
    = render 'finances/jobs_table', jobs: @jobs

%hr

= form_tag weeks_finances_path, method: :get do
  = label_tag :from_week
  = date_field_tag :from_week, params[:from_week]
  = label_tag :to_week
  = date_field_tag :to_week, params[:to_week]
  = submit_tag 'Go', class: 'btn'

%table#finances-weeks.table.table-bordered.table-fixed-header
  %thead
    %tr
      %th{width: 150} Week starting
      %th Jobs
      %th Total value
      %th Value of completed
      %th Value of completed and paid
      %th Amount outstanding of completed
      %th Amount paid this week
      %th Amount paid - Value of completed
  %tbody
    - jobs_total = 0
    - value_total = Money.new(0, 'GBP')
    - completed_value_total = Money.new(0, 'GBP')
    - paid_value_total = Money.new(0, 'GBP')
    - outstanding_value_total = Money.new(0, 'GBP')
    - amount_paid_total = Money.new(0, 'GBP')
    - amount_paid_minus_completed_value = Money.new(0, 'GBP')
    - @weeks.each do |week|
      %tr.clickable-row{class: week == current_business.current_week && "current-week", data: {resource: 'finances', id: week.id}}
        %td.clickable= week.start_date.to_s(:long)
        %td.clickable= week.jobs_count.tap { |count| jobs_total += count }
        %td.clickable= week.value.tap { |value| value_total += value }.format
        %td.clickable= week.completed_value.tap { |value| completed_value_total += value }.format
        %td.clickable= week.paid_value.tap { |value| paid_value_total += value }.format
        %td.clickable= week.outstanding_value.tap { |value| outstanding_value_total += value }.format
        %td.clickable= week.amount_paid.tap { |value| amount_paid_total += value }.format
        %td.clickable= (week.amount_paid - week.completed_value).tap { |value| amount_paid_minus_completed_value += value }.format
    %tr
      %td{colspan: 8} &nbsp;
    %tr
      %th{width: 150} &nbsp;
      %th Jobs
      %th Total value
      %th Value of completed
      %th Value of completed and paid
      %th Amount outstanding of completed
      %th Amount paid
      %th Amount paid - Value of completed
    %tr
      %td &nbsp;
      %td= jobs_total
      %td= value_total.format
      %td= completed_value_total.format
      %td= paid_value_total.format
      %td= outstanding_value_total.format
      %td= amount_paid_total.format
      %td= amount_paid_minus_completed_value.format
    - weeks_count = @weeks.count
    %tr
      %th{colspan: 8} Averages (over #{weeks_count} weeks)
    %tr
      %td &nbsp;
      %td= jobs_total / weeks_count
      %td= (value_total / weeks_count).format
      %td= (completed_value_total / weeks_count).format
      %td= (paid_value_total / weeks_count).format
      %td= (outstanding_value_total / weeks_count).format
      %td= (amount_paid_total / weeks_count).format
      %td= (amount_paid_minus_completed_value / weeks_count).format