config/routes.rb
NclarkWindows::Application.routes.draw do



  devise_for :businesses, controllers: { registrations: 'businesses/registrations' }

  resources :businesses, only: [:update]
  get 'businesses', to: 'pages#home'

  resources :default_customer_details, except: [:index, :show] do
    collection do
      put :update_ordering, format: :json
    end

    member do
      get :toggle_visible_in_work_list, format: :js
    end
  end

  resources :customer_detail_categories, except: [:index, :show] do
    collection do
      put :update_ordering, format: :json
    end
  end

  resources :areas

  resources :customers do
    resources :risks_assessments do
      member do
        put 'check_assessment', to: 'risks_assessments#check_assessment', as: :check_risks_assessment
      end
    end
    resources :customer_notes, only: [:create, :destroy], format: :js
    resources :attachments, only: [:create, :destroy]
    resources :payments, except: :show

    member do
      post :create_job_for_current_week, format: :js
      get :activate
      get :deactivate
    end

    collection do
      get :clear_quick_search_params
    end
  end

  resources :jobs, except: [:index] do
    resources :job_notes, only: [:create, :destroy], format: :js

    member do
      get :mark_as_risk_checked, format: :js
      get :mark_as_completed, format: :js
      get :unmark_as_completed, format: :js
      put :mark_as_paid, format: :js
      put :update_notes, format: :js
      put :update_price, format: :json
      put :update_invoice_number, format: :json
      get :quick_new
      post :quick_create
    end
  end

  resources :work_list_categories, except: [:index, :show] do
    member do
      patch :update_balance_date_from
    end
  end

  resources :work_lists, only: [:show] do
    resources :work_list_notes, only: [:create, :destroy], format: :js

    collection do
      get :view, format: :js
    end

    member do
      put :update_tag, format: :json
      put :move_jobs, format: :json
      get :mark_as_completed
      get :mark_as_incompleted
      post :customer_search, format: :js
      get :add_job_for_customer, format: :js
      patch :update_target
      put :update_job_ordering, format: :json
      get :reset_job_ordering
      get :get_simple_show, format: :js
    end
  end

  resources :weeks, only: [:index, :show, :edit, :update] do
    collection do
      get :generate_cycle
    end

    member do
      get :work_lists
      patch :pull_work
      patch :push_work
    end
  end

  resources :users, except: [:show] do
    collection do
      get :sign_in
      post :sign_in, to: "users#sign_in_submit"
      get :sign_out_user
    end
  end

  resources :bookmarks, only: [:create], format: :json do
    collection do
      delete :destroy
    end
  end

  resources :finances, only: [:index, :show] do
    collection do
      get :weeks
      post :export
      get :get_export_status, format: :json
    end
  end

  resources :targets, only: [:index, :show]
  resources :expenses

  resources :customer_search_queries, only: [] do
    collection do
      post :search, format: :json
      get :get_search_status, format: :json
      delete :clear_search
      delete :remove_customer_from_search_results
      post :export
      get :get_export_status, format: :json
    end
  end

  get :work_list_settings, to: 'pages#work_list_settings'
  get :toggle_work_list_payment_method, to: 'businesses#toggle_work_list_payment_method', format: :js

  root to: 'pages#home'
end

app/models/risks_assessment.rb
# == Schema Information
#
# Table name: risks_assessments
#
#  id                        :integer          not null, primary key
#  yes                       :boolean
#  no                        :boolean
#  too_high                  :boolean
#  ground_not_safe           :boolean
#  no_clear_access_to_window :boolean
#  work_from_inside          :boolean
#  footed_ladder             :boolean
#  folded_ladder             :boolean
#  work_positioning_system   :boolean
#  read_and_wash             :boolean
#  secured_ladder            :boolean
#  harness                   :boolean
#  bar                       :boolean
#  other                     :string(255)
#  why                       :text
#  operative                 :string(255)
#  date                      :date
#  user_id                   :integer
#  customer_id               :integer
#  created_at                :datetime
#  updated_at                :datetime
#  not_all                   :boolean
#  worklist_id               :integer
#

class RisksAssessment < ActiveRecord::Base
  belongs_to :customer
  belongs_to :user
  has_many :users
  has_many :risksusers
  validate :check_yes_and_no

  def check_yes_and_no
    if (self.yes && self.no && self.not_all)||(self.yes==false && self.no ==false && self.not_all ==false)
      errors.add(:yes,'/No/Not_all cannot the same.')
    end
  end

  def user_in(user)
    RisksUser.where(user_id:user, risks_assessment_id:self.id, risk_cheacked:true)
  end

  def time_checked(user)
    RisksUser.find(user_in(user).pluck(:id))
  end

  def who_checked
    User.find(RisksUser.where(risks_assessment_id:self.id, risk_cheacked:true).pluck(:user_id))
  end

  def name_user
    User.find(self.operative)
  end

  def user_in_today(user_id)
    self.user_in(user_id).pluck(:created_at).last.strftime("%m/%d/%Y")
  end

  def accept(user_id)
    RisksUser.create(user_id: user_id, risks_assessment_id:self.id, date:Time.now.strftime("%d %b %Y %k:%M"), risk_cheacked: true)
  end

  def already_have?(user_id)
    if RisksUser.find_by(risks_assessment_id: self.id, user_id:user_id).date.strftime("%m/%d/%Y") == Date.today.strftime("%m/%d/%Y")
      return true
    else
      return false
    end
  end

end

app/controllers/risks_assessments_controller.rb
class RisksAssessmentsController < ApplicationController
  before_action :authenticate_business!
  before_action :authenticate_user!
  before_action :set_risks_assessment, only: [:show, :edit, :update, :destroy, :check_assessment]
  before_action :set_user, only: [:create, :update]
  before_action :set_customer, only: [:create, :new, :edit, :index]
  before_action :set_workList, only: [:show, :index, :new, :check_assessment]
  # GET /risks_assessments
  # GET /risks_assessments.json
 def index
   @risks_assessments = RisksAssessment.where(customer_id:@customer)
   @customer_with_risk_assessment = @risks_assessments.first
 end
  # GET /risks_assessments/1
  # GET /risks_assessments/1.json
  def show

  end

  # GET /risks_assessments/new
  def new
    @risks_assessment = RisksAssessment.new
  end

  # GET /risks_assessments/1/edit
  def edit
  end

  # POST /risks_assessments
  # POST /risks_assessments.json
  def create
    @risks_assessment = RisksAssessment.new(risks_assessment_params)
    @risks_assessment.customer_id = @customer.id
    @risks_assessment.operative = current_user.name
    @risks_assessment.user_id = current_user.id
    @risks_assessment.date = Time.now.strftime("%d %b %Y %k:%M")
    @customer.customer_details_cache["Address Line"]
    respond_to do |format|
      if @risks_assessment.save
        format.html { redirect_to work_list_path(@risks_assessment.worklist_id), notice: 'Risks assessment was successfully created.' }
        format.json { render action: 'show', status: :created, location: @risks_assessment }
        @risks_assessment.accept(current_user.id)
      else
        format.html { render action: 'new' }
        format.json { render json: @risks_assessment.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /risks_assessments/1
  # PATCH/PUT /risks_assessments/1.json
  def update
    @risks_assessment.operative= current_user.name
    respond_to do |format|
      if @risks_assessment.update(risks_assessment_params)
        format.html { redirect_to customer_path(@risks_assessment.customer), notice: 'Risks assessment was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: 'edit' }
        format.json { render json: @risks_assessment.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /risks_assessments/1
  # DELETE /risks_assessments/1.json
  def destroy
    @risks_assessment.destroy
    respond_to do |format|
      format.html { redirect_to customer_path(@risks_assessment.customer), notice: 'Risks assessment was successfully deleted.' }
      format.json { head :no_content }
    end
  end

  def check_assessment
    RisksUser.create(risks_assessment_id:@risks_assessment.id, user_id:current_user.id, risk_cheacked:true, date:Time.now.strftime("%d %b %Y %k:%M"))
      redirect_to customer_risks_assessment_path(@risks_assessment.customer, @risks_assessment, :workList => @work_list), success:"Thanks for checking this risk assessment."
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_risks_assessment
      @risks_assessment = RisksAssessment.find(params[:id])
    end

    def set_user
      @user = User.find(session[:user_id])
    end

    def set_customer
      @customer = Customer.find(params[:customer_id])
    end
    # Never trust parameters from the scary internet, only allow the white list through.
    def risks_assessment_params
      params.require(:risks_assessment).permit(:yes,:no, :not_all, :too_high, :ground_not_safe, :no_clear_access_to_window, :work_from_inside, :footed_ladder, :folded_ladder, :read_and_wash, :secured_ladder, :work_positioning_system, :bar, :other, :why, :operative, :date, :customer_id, :worklist_id)
    end

    def set_workList
      @work_list = params[:workList]
    end
end

app/helpers/risks_assessments_helper.rb
module RisksAssessmentsHelper
end

app/views/risks_assessments/_form.html.haml
= form_for [@customer, @risks_assessment] do |f|
  = render 'shared/form_errors', resource: @risks_assessment
  .row-fluid
    .span6
      %h5
        Can the windows be cleaned by a secure ladder?
    .span2
      = f.label :yes
      = f.check_box :yes, class:"form-check form-check-inline"
    .span2
      = f.label :no
      = f.check_box :no, class:"form-check form-check-inline"
    .span2
      = f.label :not_all
      = f.check_box :not_all, class:"form-check form-check-inline"
  %br
  %br

  .row-fluid
    .span3
      %p
        %h4 If NOT, Why:

    .span3
      = f.label :too_high
      = f.check_box :too_high
    .span3
      = f.label :ground_not_safe
      = f.check_box :ground_not_safe
    .span3
      = f.label :no_clear_access_to_window
      = f.check_box :no_clear_access_to_window
  %br
  %br
  .row-fluid
    .span3
      %p
        %h4 Choose preferred option:
    .span3
      = f.label :work_from_inside
      = f.check_box :work_from_inside
    .span3
      = f.label :footed_ladder
      = f.check_box :footed_ladder
    .span3
      = f.label :Work_positioning_system
      = f.check_box :work_positioning_system
  %br
  %br
  .row-fluid
    .span3
    .span3
      = f.label :secured_ladder
      = f.check_box :secured_ladder
    .span3
      = f.label :read_and_wash
      = f.check_box :read_and_wash
    .span3
      .form-group
        = f.label :other
        = f.text_field :other, class: "control-group"
  .row-fluid
    .span3
    .span3
      .form-group
        = f.label :why
        = f.text_area :why, :rows=>"3"
        = f.hidden_field :worklist_id, value: @work_list
  = f.submit "Submit", class: "btn"
  = link_to 'Back', customer_path(@customer), class:"btn"

app/views/risks_assessments/edit.html.haml
.alert.alert-info
  %h1.text-center Editing Risks Assessment
.row-fluid
  .span10
    = render 'form'

app/views/risks_assessments/index.html.haml
-if @customer_with_risk_assessment == nil
  .alert.alert-info
    There are not Risk Assessments for this job yet.
-else
  .row-fluid
    .alert.alert-info
      %h3.text-center Risk Assessments of: #{@customer_with_risk_assessment.customer.customer_details_cache["Address Line"]}
    .p.text-center Please select and press Accept button if you are agree with it.

    .span4
    .span6
      %br
      %br
        - @risks_assessments.order(date: :desc).each do |risks_assessment|
          -if risks_assessment == @risks_assessments.last
            %b
              %p
                %b By
                %td= link_to risks_assessment.operative, customer_risks_assessment_path(@customer, risks_assessment, :workList => @work_list)
                %td= risks_assessment.created_at.strftime("%d %b %Y %k:%M")
                - if current_user && current_user.super_admin? || (risks_assessment.operative == current_user.name && risks_assessment.created_at >= Time.now - 60.minutes)
                  = link_to 'Delete', customer_risks_assessment_path(@customer,risks_assessment.id),method: "delete", class: "btn", data: { confirm: "Are your sure?"}
                  Last one.
          -else
            %p
              %b By
              %td= link_to risks_assessment.operative, customer_risks_assessment_path(@customer, risks_assessment, :workList => @work_list)
              %td= risks_assessment.created_at.strftime("%d %b %Y %k:%M")
              - if current_user && current_user.super_admin? || (risks_assessment.operative == current_user.name && risks_assessment.created_at >= Time.now - 60.minutes)
                = link_to 'Delete', customer_risks_assessment_path(@customer,risks_assessment.id),method: "delete", class: "btn", data: { confirm: "Are your sure?"}

= link_to 'New Risk assessment', new_customer_risks_assessment_path(@customer, :workList => @work_list), class: 'btn'

app/views/risks_assessments/new.html.haml
.alert.alert-info
  %h1.text-center New Risks Assessment
.row-fluid
  .span10
    = render 'form'
    

app/views/risks_assessments/show.html.haml
.alert.alert-info
  %h3.text-center Risk Assessment of: #{@risks_assessment.customer.customer_details_cache["Address Line"]}
%br
%br
-if @risks_assessment.user_in(current_user.id).empty?
  .alert.alert-warning
    %h4.text-left #{current_user.name} click in Accept button if you are happy with this Risk Assessment
    = link_to "Accept", check_risks_assessment_customer_risks_assessment_path(@risks_assessment.customer.id, @risks_assessment, :workList => @work_list), class: "btn btn-small", method: 'put'
-else
  -if !@risks_assessment.already_have?(current_user.id)
    .alert.alert-info
      %h6.text-left #{current_user.name} click in Accept to use this Risk Assessment again
    = link_to "Accept", check_risks_assessment_customer_risks_assessment_path(@risks_assessment.customer.id, @risks_assessment, :workList => @work_list), class: "btn btn-small", method: 'put'
  .alert.alert-success.mt-2
    %h4.text-center #{current_user.name} Already checked this assessment on
    -@risks_assessment.time_checked(current_user.id).each do |t|
      .text-center
        #{t.created_at.strftime("%d %b %Y %k:%M")} /
- if current_user && current_user.admin? || current_user && current_user.super_admin?
  %h4 Who have checked this Risks Assessment?
  -@risks_assessment.who_checked.each do |user|
    =user.name+ " on"
    -@risks_assessment.time_checked(user.id).each do |t|
      = t.created_at.strftime("%d %b %Y %k:%M")+" / "
    %br

.row-fluid
  .span6
    %h5
      Can the windows be cleaned by secure ladder?
  .span2
    %p
      Yes:
      -if @risks_assessment.yes
        %span.label.label-inverse ✓
  .span2
    %p
      No:
      -if @risks_assessment.no
        %span.label.label-inverse ✓
  .span2
    %p
      Not All:
      -if @risks_assessment.not_all
        %span.label.label-inverse ✓
%br
%br

.row-fluid
  .span3
    %p
      %h4 If NOT, Why:

  .span3
    %p
      Too High:
      -if @risks_assessment.too_high
        %span.label.label-inverse ✓
  .span3
    %p
      Ground Not Safe:
      -if @risks_assessment.ground_not_safe
        %span.label.label-inverse ✓
  .span3
    %p
      No Clear Access to Window:
      -if @risks_assessment.no_clear_access_to_window
        %span.label.label-inverse ✓

%br
%br
.row-fluid
  .span3
    %p
      %h4 Choose preferred option:
  .span3
    %p
      Work From Inside:
      -if @risks_assessment.work_from_inside
        %span.label.label-inverse ✓

  .span3
    %p
      Footed Ladder:
      -if @risks_assessment.footed_ladder
        %span.label.label-inverse ✓
  .span3
    %p
      Work Positioning System:
      -if @risks_assessment.work_positioning_system
        %span.label.label-inverse ✓
%br
%br
.row-fluid
  .span3
  .span3
    %p
      Secured Ladder:
      -if @risks_assessment.secured_ladder
        %span.label.label-inverse ✓
  .span3
    %p
      Reach & Wash
      -if @risks_assessment.read_and_wash
        %span.label.label-inverse ✓
  .span3
    %p
      Other:
      %h5= @risks_assessment.other
%br
%br
.row-fluid
  .span3
  .span3
    %p
      Why?:
      %table#work-list-notes.table.table-bordered
        %thead
          %tr
            %td
              = simple_format(@risks_assessment.why)

    %br
.row-fluid
  .span4
    %p
      %strong Operative:
      = @risks_assessment.operative
    %p
      %strong Date:
      = @risks_assessment.created_at.strftime("%d %b %Y %I:%M%p")
    - if current_user && current_user.super_admin? || (@risks_assessment.operative == current_user.name)
      = link_to 'Edit', edit_customer_risks_assessment_path(@risks_assessment.customer, @risks_assessment), class:"btn"
    -# -if @risks_assessment.worklist_id
    -# = link_to 'Back to work list', work_list_path(@risks_assessment.customer.jobs.last.work_list_id), class:"btn"
    = link_to 'Back to work list', work_list_path(@work_list), class:"btn"