config/routes.rb
NclarkWindows::Application.routes.draw do



  devise_for :businesses, controllers: { registrations: 'businesses/registrations' }

  resources :businesses, only: [:update]
  get 'businesses', to: 'pages#home'

  resources :default_customer_details, except: [:index, :show] do
    collection do
      put :update_ordering, format: :json
    end

    member do
      get :toggle_visible_in_work_list, format: :js
    end
  end

  resources :customer_detail_categories, except: [:index, :show] do
    collection do
      put :update_ordering, format: :json
    end
  end

  resources :areas

  resources :customers do
    resources :risks_assessments do
      member do
        put 'check_assessment', to: 'risks_assessments#check_assessment', as: :check_risks_assessment
      end
    end
    resources :customer_notes, only: [:create, :destroy], format: :js
    resources :attachments, only: [:create, :destroy]
    resources :payments, except: :show

    member do
      post :create_job_for_current_week, format: :js
      get :activate
      get :deactivate
    end

    collection do
      get :clear_quick_search_params
    end
  end

  resources :jobs, except: [:index] do
    resources :job_notes, only: [:create, :destroy], format: :js

    member do
      get :mark_as_risk_checked, format: :js
      get :mark_as_completed, format: :js
      get :unmark_as_completed, format: :js
      put :mark_as_paid, format: :js
      put :update_notes, format: :js
      put :update_price, format: :json
      put :update_invoice_number, format: :json
      get :quick_new
      post :quick_create
    end
  end

  resources :work_list_categories, except: [:index, :show] do
    member do
      patch :update_balance_date_from
    end
  end

  resources :work_lists, only: [:show] do
    resources :work_list_notes, only: [:create, :destroy], format: :js

    collection do
      get :view, format: :js
    end

    member do
      put :update_tag, format: :json
      put :move_jobs, format: :json
      get :mark_as_completed
      get :mark_as_incompleted
      post :customer_search, format: :js
      get :add_job_for_customer, format: :js
      patch :update_target
      put :update_job_ordering, format: :json
      get :reset_job_ordering
      get :get_simple_show, format: :js
    end
  end

  resources :weeks, only: [:index, :show, :edit, :update] do
    collection do
      get :generate_cycle
    end

    member do
      get :work_lists
      patch :pull_work
      patch :push_work
    end
  end

  resources :users, except: [:show] do
    collection do
      get :sign_in
      post :sign_in, to: "users#sign_in_submit"
      get :sign_out_user
    end
  end

  resources :bookmarks, only: [:create], format: :json do
    collection do
      delete :destroy
    end
  end

  resources :finances, only: [:index, :show] do
    collection do
      get :weeks
      post :export
      get :get_export_status, format: :json
    end
  end

  resources :targets, only: [:index, :show]
  resources :expenses

  resources :customer_search_queries, only: [] do
    collection do
      post :search, format: :json
      get :get_search_status, format: :json
      delete :clear_search
      delete :remove_customer_from_search_results
      post :export
      get :get_export_status, format: :json
    end
  end

  get :work_list_settings, to: 'pages#work_list_settings'
  get :toggle_work_list_payment_method, to: 'businesses#toggle_work_list_payment_method', format: :js

  root to: 'pages#home'
end

app/views/shared/_customer_search.html.haml
- search_pending = current_user.has_search_pending?(request.env['REQUEST_URI'])
- completed_search = search_pending ? nil : current_user.completed_search(request.env['REQUEST_URI'])
- search_fields = options_for_select(current_business.default_customer_details.map(&:name) + ['Area', 'Notes', ['All fields', 'ALL_FIELDS']])
- sort_by_options = options_for_select(['Area', 'Regular price', ['Amount owing', 'outstanding money']] + current_business.index_default_customer_details.map(&:name))

.customer-search{class: search_pending && 'hide'}
  .customer-search-group-template.hide
    .customer-search-group{data: {customer_search_group_index: ':x'}}
      .span3.well.well-small
        .customer-search-term{data: {customer_search_term_index: ':y'}}
          = select_tag "customer_search[:x][:y][field]", search_fields, style: 'width: 90%', class: 'customer-search-field-name'
          = link_to '&times'.html_safe, '#', class: 'close pull-right'
          = text_field_tag "customer_search[:x][:y][term]", nil, style: 'width: 95%', class: 'customer-search-term-text-input'
          = select_tag "customer_search[:x][:y][term]", options_for_select(customer_area_fields_for_select), style: 'width: 100%', class: 'customer-search-term-area-input hide'
        %div
          = link_to '+', '#', class: 'btn btn-small add-customer-search-term'
      .span1{data: {customer_search_group_index: ':x'}, style: 'width: 30px'}
        = link_to '+', '#', class: 'btn btn-small add-customer-search-group'
        %span.and-text.hide AND

  .customer-sort-group-template.hide
    .customer-sort-group{data: {customer_sort_group_index: ':x'}}
      .span3.well.well-small
        = select_tag "customer_sort_by[:x][field]", sort_by_options, style: 'width: 90%'
        = link_to '&times'.html_safe, '#', class: 'close pull-right'
        = select_tag "customer_sort_by[:x][order]", options_for_select([['Ascending', 'ASC'], ['Descending', 'DESC']]), style: 'width: 100%'
        = label_tag "customer_sort_by[:x][exclude_numbering]", class: 'checkbox' do
          Exclude numbering?
          = check_box_tag "customer_sort_by[:x][exclude_numbering]"
      .span1{style: 'width: 30px', data: {customer_sort_group_index: ':x'}}
        = link_to '+', '#', class: 'btn btn-small add-customer-sort-group'
        %span.then-text.hide THEN

  .customer-search-groups.hide

  .customer-sort-groups.hide

  = link_to "Create complex search", '#', class: 'start-new-customer-search'
  .show-with-customer-search.hide
    = hidden_field_tag :customer_search_bookmarked
    = hidden_field_tag :customer_search_assigned
    = hidden_field_tag :customer_search_active, 'applied'
    = hidden_field_tag :customer_search_owing
    %span.icon.icon-bookmark.customer-search-toggle{data: {toggle: 'tooltip', field: 'customer_search_bookmarked'}.merge(bookmarked_toggle_values)}
    %span.icon.icon-check.customer-search-toggle{data: {toggle: 'tooltip', field: 'customer_search_assigned'}.merge(assigned_toggle_values)}
    %span.icon.icon-thumbs-up.customer-search-toggle{data: {toggle: 'tooltip', field: 'customer_search_active'}.merge(active_toggle_values)}
    %span.icon.icon-screenshot.customer-search-toggle{data: {toggle: 'tooltip', field: 'customer_search_owing'}.merge(owing_toggle_values)}
  %br
  = link_to "Search", '#', class: 'customer-search-submit show-with-customer-search btn hide'

.customer-search-pending{class: !search_pending && 'hide'}
  = image_tag "ajax-loader.gif"

- if completed_search.present?
  .customer-search-completed
    %div
      = formatted_customer_search_query(completed_search)
    = link_to "Clear search", clear_search_customer_search_queries_path, data: {method: :delete}
    .customer-search-export{class: completed_search.xlsx_export_pending? && 'pending'}
      - if completed_search.xlsx_export_pending?
        = image_tag "ajax-loader.gif"
      - else
        - if completed_search.xlsx_export_finished?
          = link_to completed_search.xlsx_file.url do
            Download XLSX file (generated #{completed_search.xlsx_export_finished_at.strftime("%d %b %Y %H:%M")})
        %div
          = link_to "Export search", '#export-search-modal', data: {toggle: 'modal'}
          #export-search-modal.modal.hide{style: 'width: 600px; margin-left: -300px'}
            .modal-body
              = form_tag export_customer_search_queries_path do
                %div
                  %strong Fields to export
                - current_business.customer_detail_categories.each_slice(3) do |category_slice|
                  .row
                    - category_slice.each do |category|
                      .span2
                        %strong= category.name
                        - category.default_customer_details.each do |detail|
                          = label_tag "export[export_customer_details][#{detail.name}]", class: 'checkbox' do
                            = detail.name
                            = check_box_tag "export[export_customer_details][#{detail.name}]"
                .row
                  .span2
                    %strong Other
                    - ['Area', 'Regular price', 'Last clean', 'Amount owing', 'ID'].each do |item|
                      = label_tag "export[export_other_details][#{item}]", class: 'checkbox' do
                        = item
                        = check_box_tag "export[export_other_details][#{item}]"
                = submit_tag "Export search", class: 'btn'

%div
  %hr
  = form_tag request.env['REQUEST_URI'], class: 'form-search customer-quick-search', method: :get do
    = hidden_field_tag :quick_search_reset
    = hidden_field_tag :quick_search_bookmarked, params[:quick_search_bookmarked]
    = hidden_field_tag :quick_search_assigned, params[:quick_search_assigned]
    = hidden_field_tag :quick_search_active, params[:quick_search_active] || 'applied'
    = hidden_field_tag :quick_search_owing, params[:quick_search_owing]
    = text_field_tag "quick_search_term", params[:quick_search_term], class: 'search-query', placeholder: 'Quick Search'
    = select_tag :quick_search_field, options_for_select(customer_details_fields_for_select('Search in all fields'), params[:quick_search_field])
    = select_tag :quick_search_sort, options_for_select(customer_sort_fields_for_select('No sorting') + [['Area', 'Area'], ['Amount owing', 'outstanding money']], params[:quick_search_sort])
    = select_tag :quick_search_area_id, options_for_select([['Group by area', 'sort']] + customer_area_fields_for_select, params[:quick_search_area_id]), :prompt => "Any area"
    %span.icon.icon-bookmark.customer-search-toggle{data: {toggle: 'tooltip', field: 'quick_search_bookmarked'}.merge(bookmarked_toggle_values)}
    %span.icon.icon-check.customer-search-toggle{data: {toggle: 'tooltip', field: 'quick_search_assigned'}.merge(assigned_toggle_values)}
    %span.icon.icon-thumbs-up.customer-search-toggle{data: {toggle: 'tooltip', field: 'quick_search_active'}.merge(active_toggle_values)}
    %span.icon.icon-screenshot.customer-search-toggle{data: {toggle: 'tooltip', field: 'quick_search_owing'}.merge(owing_toggle_values)}
    = submit_tag '>', class: 'btn'
    - if quick_search_params_present?
      = link_to "Clear search", clear_quick_search_params_customers_path

:javascript
  $(function() {
    var form = $('form.customer-quick-search');
    form.find('input[name="quick_search_term"]').on('change', function() {
      var resetInput = form.find('input:hidden[name="quick_search_reset"]');
      if ($(this).val() === "") {
        resetInput.val('true');
      } else {
        resetInput.val('false');
      }
    });
  });

app/views/shared/_customer_sort_fields.html.haml
- in_weeks_view ||= false
= form_tag url_for, method: :get, class: "customer-sort-form" do
  = hidden_field_tag :reset
  %div
    .customer-sort-field
      = label_tag :sort_by
      = select_tag :sort_by, options_for_select(customer_sort_fields_for_select, params[:sort_by])
    .customer-sort-field
      = label_tag :order
      = select_tag :order, options_for_select([['Ascending', 'asc'], ['Descending', 'desc']], params[:order])
    .customer-sort-field
      = label_tag :blank_value_order, "Blank values come"
      = select_tag :blank_value_order, options_for_select([['Last', 'last'], ['First', 'first']], params[:blank_value_order])
    .customer-sort-field
      = label_tag :area_id, "Area"
      = select_tag :area_id, options_for_select(customer_area_fields_for_select, params[:area_id]), :prompt => "Any"
  %div
    .customer-sort-field
      = label_tag :search_term
      = text_field_tag :search_term, params[:search_term]
    .customer-sort-field
      = label_tag :search_sort_by, "Only search 'Sort by' field?"
      = check_box_tag :search_sort_by, '1', params[:search_sort_by] == '1'
    .customer-sort-field
      = label_tag :use_trimmed_value, "Exclude beginning numbers?"
      = check_box_tag :use_trimmed_value, '1', params[:use_trimmed_value] == '1'
    .customer-sort-field
      = label_tag :group_by_area, "Group by area?"
      = check_box_tag :group_by_area, '1', params[:group_by_area] == '1'
    .customer-sort-field
      = label_tag :weak_group_by_area, "Group by sort by?"
      = check_box_tag :weak_group_by_area, '1', params[:weak_group_by_area] == '1'
    .customer-sort-field
      = label_tag :show_bookmarked, "Show bookmarked?"
      = check_box_tag :show_bookmarked, '1', params[:show_bookmarked] == '1'
    .customer-sort-field
      = label_tag :show_unassigned_jobs, "Show unassigned jobs?"
      = check_box_tag :show_unassigned_jobs, '1', params[:show_unassigned_jobs] == '1'
    .customer-sort-field
      = submit_tag "Go", class: "btn"

:javascript
  $(function() {
    var form = $('form.customer-sort-form');
    form.find('select[name="sort_by"], select[name="area_id"], input[name="search_term"]').on('change', function() {
      var resetInput = form.find('input:hidden[name="reset"]');
      if ($(this).val() === "") {
        resetInput.val('true');
      } else {
        resetInput.val('false');
      }
    });
  });

app/views/shared/_form_errors.html.haml
- if resource.errors.present?
  .alert.alert-error
    The following errors prevented the #{resource.class.name.underscore.humanize.downcase} from being saved:
    %ul
      - resource.errors.full_messages.each do |error|
        %li= error