config/routes.rb
NclarkWindows::Application.routes.draw do



  devise_for :businesses, controllers: { registrations: 'businesses/registrations' }

  resources :businesses, only: [:update]
  get 'businesses', to: 'pages#home'

  resources :default_customer_details, except: [:index, :show] do
    collection do
      put :update_ordering, format: :json
    end

    member do
      get :toggle_visible_in_work_list, format: :js
    end
  end

  resources :customer_detail_categories, except: [:index, :show] do
    collection do
      put :update_ordering, format: :json
    end
  end

  resources :areas

  resources :customers do
    resources :risks_assessments do
      member do
        put 'check_assessment', to: 'risks_assessments#check_assessment', as: :check_risks_assessment
      end
    end
    resources :customer_notes, only: [:create, :destroy], format: :js
    resources :attachments, only: [:create, :destroy]
    resources :payments, except: :show

    member do
      post :create_job_for_current_week, format: :js
      get :activate
      get :deactivate
    end

    collection do
      get :clear_quick_search_params
    end
  end

  resources :jobs, except: [:index] do
    resources :job_notes, only: [:create, :destroy], format: :js

    member do
      get :mark_as_risk_checked, format: :js
      get :mark_as_completed, format: :js
      get :unmark_as_completed, format: :js
      put :mark_as_paid, format: :js
      put :update_notes, format: :js
      put :update_price, format: :json
      put :update_invoice_number, format: :json
      get :quick_new
      post :quick_create
    end
  end

  resources :work_list_categories, except: [:index, :show] do
    member do
      patch :update_balance_date_from
    end
  end

  resources :work_lists, only: [:show] do
    resources :work_list_notes, only: [:create, :destroy], format: :js

    collection do
      get :view, format: :js
    end

    member do
      put :update_tag, format: :json
      put :move_jobs, format: :json
      get :mark_as_completed
      get :mark_as_incompleted
      post :customer_search, format: :js
      get :add_job_for_customer, format: :js
      patch :update_target
      put :update_job_ordering, format: :json
      get :reset_job_ordering
      get :get_simple_show, format: :js
    end
  end

  resources :weeks, only: [:index, :show, :edit, :update] do
    collection do
      get :generate_cycle
    end

    member do
      get :work_lists
      patch :pull_work
      patch :push_work
    end
  end

  resources :users, except: [:show] do
    collection do
      get :sign_in
      post :sign_in, to: "users#sign_in_submit"
      get :sign_out_user
    end
  end

  resources :bookmarks, only: [:create], format: :json do
    collection do
      delete :destroy
    end
  end

  resources :finances, only: [:index, :show] do
    collection do
      get :weeks
      post :export
      get :get_export_status, format: :json
    end
  end

  resources :targets, only: [:index, :show]
  resources :expenses

  resources :customer_search_queries, only: [] do
    collection do
      post :search, format: :json
      get :get_search_status, format: :json
      delete :clear_search
      delete :remove_customer_from_search_results
      post :export
      get :get_export_status, format: :json
    end
  end

  get :work_list_settings, to: 'pages#work_list_settings'
  get :toggle_work_list_payment_method, to: 'businesses#toggle_work_list_payment_method', format: :js

  root to: 'pages#home'
end

app/models/work_list.rb
# == Schema Information
#
# Table name: work_lists
#
#  id                        :integer          not null, primary key
#  work_list_category_id     :integer          not null
#  week_id                   :integer          not null
#  day                       :integer          not null
#  created_at                :datetime
#  updated_at                :datetime
#  token_1                   :string(255)
#  token_2                   :string(255)
#  tag                       :string(255)
#  completed                 :boolean          default(FALSE)
#  target_cents              :integer          default(0)
#  date_cache                :date
#  job_counter_cache         :integer
#  completed_job_cents_cache :integer
#  target_delta_cents_cache  :integer          default(0)
#  visible                   :boolean          default(FALSE)
#  publication_date          :date
#  publication_time          :time

class WorkList < ActiveRecord::Base

  belongs_to :work_list_category
  belongs_to :week
  has_many :jobs, dependent: :nullify
  has_many :work_list_notes, dependent: :destroy
  has_many :work_list_workers, dependent: :destroy
  has_many :users, through: :work_list_workers

  after_create :generate_tokens!
  after_create :update_date_cache!
  before_save :update_tag_if_blank
  after_save :update_job_caches!

  validates_presence_of :work_list_category
  validates_length_of :tag, maximum: 250

  scope :in_future_weeks, -> { where('work_lists.week_id IN (SELECT weeks.id FROM weeks WHERE weeks.start_date > ?)', Date.today) }
  scope :by_date, lambda { |asc_desc = :asc| order("work_lists.date_cache #{asc_desc.to_s.upcase}") }

  scope :in_date_range, lambda { |start_date, finish_date|
    begin
      start_date = Date.parse(start_date)
    rescue
      start_date = nil
    end
    begin
      finish_date = Date.parse(finish_date)
    rescue
      finish_date = nil
    end
    if start_date.present? && finish_date.present?
      where('work_lists.date_cache >= ? AND work_lists.date_cache <= ?', start_date, finish_date)
    elsif start_date.present?
      where('work_lists.date_cache >= ?', start_date)
    elsif finish_date.present?
      where('work_lists.date_cache <= ?', finish_date)
    else
      all
    end
  }

  composed_of :target,
    class_name: "Money",
    mapping: [["target_cents", "cents"]],
    constructor: Proc.new { |cents| Money.new(cents || 0, 'GBP') },
    converter: Proc.new { |rp| rp.to_money('GBP') }

  def name(week_override = nil)
    "#{((week_override || week).start_date + day.days).to_s(:short)} - #{work_list_category.name}"
  end

  def url_token_params
    {:t1 => token_1, :t2 => token_2}
  end

  def full_name
    if work_list_category.name != tag
      "#{work_list_category.name} - #{tag}"
    else
      tag
    end
  end

  def full_name_with_date(week_override = nil)
    "#{((week_override || week).start_date + day.days).strftime("%a %d %b")} - #{full_name}"
  end

  def job_total_price_including_vat
    jobs.inject(Money.new(0, 'GBP')) { |total, job| total + job.price_including_vat }
  end

  def job_total_outstanding_including_vat
    jobs.inject(Money.new(0, 'GBP')) { |total, job| total + job.customer.outstanding_money }
  end

  def completed_job_total_price_including_vat
    jobs.completed.inject(Money.new(0, 'GBP')) { |total, job| total + job.price_including_vat }
  end

  def paid_job_total_price_including_vat
    jobs.paid.inject(Money.new(0, 'GBP')) { |total, job| total + job.price_including_vat }
  end

  def date
    @date ||= (week.start_date + day.days).to_date
  end

  def mark_as_completed!
    update_column(:completed, true)
  end

  def mark_as_incompleted!
    update_column(:completed, false)
  end

  def html_classes
    (job_counter_cache > 0 ? 'work-list-with-jobs ' : '') + (completed? ? 'work-list-signed-off' : '')
  end

  def apply_target?
    if @apply_target.nil?
      @apply_target = !job_counter_cache.zero?
    end
    @apply_target
  end

  def target_met?
    if @target_met.nil?
      @target_met = completed_job_cents_cache >= target_cents
    end
    @target_met
  end

  def target_delta_cents
    target_delta_cents_cache
  end

  def target_delta
    Money.new(target_delta_cents, 'GBP')
  end

  def target_met_html_classes
    if !apply_target? || date_cache > Date.today
      ""
    elsif target_delta_cents >= 0
      "target-met"
    elsif target_delta_cents < 0
      "target-not-met"
    else
      ""
    end
  end

  def update_job_ordering(new_job)
    not_new_job_jobs = self.jobs.where("jobs.id != ?", new_job.id)
    if not_new_job_jobs.count > 0 && not_new_job_jobs.all? { |job| job.work_list_order.present? }
      jobs = self.jobs.where("jobs.start_time IS NOT NULL").where("jobs.id != ?", new_job.id)
      if jobs.count.zero? || new_job.start_time.blank?
        if new_job.start_time.present?
          self.jobs.where("jobs.id != ?", new_job.id).each do |job|
            job.update_column(:work_list_order, job.work_list_order + 1)
          end
          new_job.update_column(:work_list_order, 0)
        else
          new_job.update_column(:work_list_order, self.jobs.where("jobs.id != ?", new_job.id).count)
        end
      else
        jobs_in_work_list_order = jobs.work_list_order.to_a

        smallest_time_difference = nil
        smallest_time_difference_job = nil
        jobs_in_work_list_order.each do |job|
          time = job.start_time - new_job.start_time
          if smallest_time_difference_job.nil? || time.abs < smallest_time_difference.abs
            smallest_time_difference = time
            smallest_time_difference_job = job
          end
        end
        if smallest_time_difference < 0
          self.jobs.where('jobs.work_list_order > ?', smallest_time_difference_job.work_list_order).each do |job|
            job.update_column(:work_list_order, job.work_list_order + 1)
          end
          new_job.update_column(:work_list_order, smallest_time_difference_job.work_list_order + 1)
        else
          self.jobs.where('jobs.work_list_order >= ?', smallest_time_difference_job.work_list_order).each do |job|
            job.update_column(:work_list_order, job.work_list_order + 1)
          end
          new_job.update_column(:work_list_order, smallest_time_difference_job.work_list_order)
        end
      end
    else
      self.jobs.update_all(work_list_order: nil)
    end
  end

  def update_job_caches!
    cjcc = jobs.completed.pluck(:cents).inject(0, &:+)
    update_columns(job_counter_cache: jobs.count,
                   completed_job_cents_cache: cjcc,
                   target_delta_cents_cache: cjcc - target_cents)
    work_list_category.update_balance!
  end

  # def user_work_lists(day_index, user)
  #   if user
  #     if user.hasRole('Admin') || user.hasRole('Super_Admin')
  #       work_lists.where(day: day_index)
  #     elsif user.hasRole('Team_leader')
  #       work_lists.where(day: day_index, work_list_category_id: user.work_list_category.id)
  #     end
  #   end
  # end

  def is_user_in_risk_assement?(risks_assessment_id, user_id)
    RisksUser.where(risks_assessment_id: risks_assessment_id, user_id: user_id).empty?
  end

  def already_accept_any_risks_assessment(risks_assessment_id, user_id)
    RisksUser.find_by(risks_assessment_id: risks_assessment_id, user_id: user_id).created_at.strftime("%m/%d/%Y")==Date.today.strftime("%m/%d/%Y")
  end


private
  def generate_tokens!
    update_attributes(token_1: SecureRandom.uuid, token_2: SecureRandom.uuid)
  end

  def update_date_cache!
    update_column(:date_cache, week.start_date + day)
  end

  def update_tag_if_blank
    if tag.blank?
      self.tag = work_list_category.tag
    end
  end
end

app/views/work_lists/_customer_search_results.html.haml
%table#customer-search-results-table.table.table-bordered
  %thead
    %th &nbsp;
    %th Last clean
    - @index_default_customer_details_names.each do |name|
      %th= name
    %th Price
    %th Price inc VAT
    %th &nbsp;
  %tbody
    - @customers.each do |customer|
      - color_added = false
      %tr{class: customer.current_week_job_html_classes(week_override: @work_list.week), data: {customer_id: customer.id}}
        %td.checkbox-toggle{style: "background-color: ##{customer.area.color}"}
          &nbsp;
        %td= customer.last_clean_string
        - index_details = customer.index_details(true, @index_default_customer_details_names)
        - @index_default_customer_details_names.each_with_index do |name, i|
          %td{style: !color_added && customer.color.present? ? "background-color:##{customer.color}" : ''}
            - color_added = true
            - if params[:sort_by] == name && params[:use_trimmed_value] == '1'
              = index_details.find { |detail| detail.name == name }.try(:trimmed_value)
            - else
              = index_details.find { |detail| detail.name == name }.try(:value)
        %td= customer.regular_price.format
        %td= customer.regular_price_including_vat.format
        %td
          = link_to "Add", add_job_for_customer_work_list_path(@work_list, customer_id: customer.id), remote: true
          |
          = link_to "+ edit", add_job_for_customer_work_list_path(@work_list, customer_id: customer.id, edit_after_save: true), remote: true

app/views/work_lists/_show.html.haml
- default_vat_rate = work_list.work_list_category.business.default_vat_rate
- payment_methods_options = work_list.work_list_category.business.work_list_payment_methods_array.map { |pm| [pm.titleize, pm] } + [['None', nil]]
- use_checkboxes ||= false
- non_sortable ||= false

%table.table.table-bordered.work-list-table{class: business_signed_in? && !non_sortable && 'ui-sortable', data: {work_list_id: work_list.id, t1: work_list.token_1, t2: work_list.token_2}}
  %thead
    %th.hidden-print &nbsp;
    %th Time
    %th Invoice No.
    - @work_list_default_customer_details_names.each do |name|
      %th= name
    %th Amount
    %th VAT
    %th Total
    %th.hidden-print
      Out
      %br
      standing
    %th.hidden-print Completed

    %th
      %span.hidden-print Paid
      %span.visible-print Paid by cash
      %span.visible-print Paid by cheque
    %th.hidden-print Risks Assessment
    - if business_signed_in?
      %th.hidden-print &nbsp;
  %tbody
    - odd_row = true
    - work_list.jobs.work_list_order.each do |job|
      - odd_row = !odd_row
      - if business_signed_in?
        - url_params = {}
      - else
        - url_params = job.work_list.url_token_params
      %tr.work-list-job.clickable-row{class: (odd_row ? 'odd' : ''), id: "job-#{job.id}", data: {resource: 'customers', id: job.customer_id, job_id: job.id, record_id: job.id, extra_params: business_signed_in? || "job_id=#{job.id}&t1=#{work_list.token_1}&t2=#{work_list.token_2}"}}
        - if use_checkboxes
          %td.checkbox-toggle.hidden-print{style: "background-color: ##{job.customer.area.color}"}
            %input{type: 'checkbox', data: {job_id: job.id}}
        - else
          %td.clickable.hidden-print{style: "background-color: ##{job.customer.area.color}"}
            &nbsp;
        %td.clickable
          = job.formatted_time
        %td
          = render 'work_lists/editable_invoice_number_td', job: job
        - job.customer.tap do |customer|
          - color_added = false
          - index_details = customer.index_details(true, @work_list_default_customer_details_names)
          - @work_list_default_customer_details_names.each_with_index do |name, i|
            %td.clickable{style: !color_added && customer.color.present? ? "background-color:##{customer.color}" : ''}
              - color_added = true
              - if params[:sort_by] == name && params[:use_trimmed_value] == '1'
                = index_details.find { |detail| detail.name == name }.try(:trimmed_value)
              - else
                = index_details.find { |detail| detail.name == name }.try(:value)
        %td
          - if current_user && (current_user.admin? || current_user.super_admin? || current_user.team_leader?)
            = render 'work_lists/editable_price_excluding_vat_td', job: job, default_vat_rate: default_vat_rate
        %td.clickable
          - if current_user && (current_user.admin? || current_user.super_admin? || current_user.team_leader?)
            %span{style: 'margin-right: -4px'} &pound;
            %span.price-vat
              = job.vat(true, default_vat_rate)
        %td
          - if current_user && (current_user.admin? || current_user.super_admin? || current_user.team_leader?)
            = render 'work_lists/editable_price_including_vat_td', job: job, default_vat_rate: default_vat_rate
        -# - if current_user && (current_user.admin? || current_user.super_admin? || current_user.team_leader?)
        %td.clickable.hidden-print
          %span{style: 'margin-right: -4px'} &pound;
          %span.customer-outstanding-money
            = job.customer.outstanding_money
        %td.job-completed.hidden-print
          - if job.completed?
            = image_tag('tick.png')
          - else
            = link_to "Completed?", mark_as_completed_job_path(job, url_params), class: "btn btn-small", remote: true
        %td.job-paid
          %span.hidden-print
            - if current_user && (current_user.admin? || current_user.super_admin? || current_user.team_leader?)
              - if job.paid?
                = job.total_payment_amount.format
                \-
                = job.total_payment_method.titleize
              - else
                = link_to "Paid?", '#', class: "mark-as-paid btn btn-small"
                .modal.job-paid-form.hide
                  .modal-body
                    = form_for job, url: mark_as_paid_job_path(job, url_params), method: :put, remote: true do |f|
                      %div
                        = f.label :payment_method
                        = f.select :payment_method, payment_methods_options
                      %div
                        = f.label :payment_amount, "Amount paid"
                        = f.text_field :payment_amount, value: job.price
                      %div
                        = f.label :invoice_number
                        = f.text_field :invoice_number
                      %br
                      = f.submit "Mark as paid", class: 'btn btn-small'
                      = image_tag "ajax-loader.gif", class: "hide ajax-loader"
        %td.job-risk_checked.hidden-print
          - if job.customer.risks_assessments.count==0
            =link_to "New", new_customer_risks_assessment_path(job.customer.id, :workList => @work_list)
            .alert.alert-danger Empty!!!!
          - else
            =link_to "Show", customer_risks_assessments_path(job.customer.id, :workList => @work_list)
            -if work_list.is_user_in_risk_assement?(job.customer.risks_assessments.last.id, current_user.id)
              .alert.alert-danger Check today
            -elsif !work_list.already_accept_any_risks_assessment(job.customer.risks_assessments.last.id, current_user.id)
              .alert.alert-danger Check today
            -else
              = image_tag('tick.png')
        %td.job-notes
          %span.hidden-print
            = link_to (job.job_notes.present? ? "Edit notes" : "Add notes"), '#', class: 'edit-notes'
            .modal.job-notes-form.hide
              .modal-body
                = render 'jobs/notes_form', job: job

        - if business_signed_in?
          - if current_user && (current_user.admin? || current_user.super_admin?)
            %td.hidden-print
              = link_to "Edit job", edit_job_path(job)
      - if job.job_notes.present?
        %tr.work-list-job-notes.ui-state-disabled{class: odd_row && 'odd', id: "job-#{job.id}-notes", data:{job_id: job.id}}
          %td &nbsp;
          = render 'work_lists/job_notes_td', job: job
    %tr.ui-state-disabled
      - if current_user && (current_user.admin? || current_user.super_admin? || current_user.team_leader?)
        %th{colspan: @work_list_default_customer_details_names.length + 5, style: 'text-align:right'}
          Total
        %td= work_list.job_total_price_including_vat.format
        %td.hidden-print= work_list.job_total_outstanding_including_vat.format
        %td.hidden-print
          %strong= work_list.completed_job_total_price_including_vat.format
        %td.hidden-print= work_list.paid_job_total_price_including_vat.format
        %td.hidden-print &nbsp;
        %td{colspan: 2}

app/views/work_lists/_simplified_show.html.haml
- payment_methods_options = current_business.work_list_payment_methods_array.map { |pm| [pm.titleize, pm] } + [['None', nil]]
- default_vat_rate = current_business.default_vat_rate

%table.table.table-bordered.work-list-table{data: {work_list_id: work_list.id}}
  %thead
    %th.hidden-print &nbsp;
    %th Time
    %th Invoice No.
    - @work_list_default_customer_details_names.each do |name|
      %th= name
    %th Amount
    %th VAT
    %th Total
    %th.hidden-print
      Out
      %br
      standing
    %th.hidden-print Completed
    %th
      %span.hidden-print Paid
      %span.visible-print Paid by cash
    %th
      %span.hidden-print &nbsp;
      %span.visible-print Paid by cheque
    %th.hidden-print &nbsp;
  %tbody
    - odd_row = true
    - work_list.jobs.work_list_order.each do |job|
      - odd_row = !odd_row
      %tr.work-list-job.clickable-row{class: (odd_row ? 'odd' : ''), id: "job-#{job.id}", data: {resource: 'customers', id: job.customer_id, job_id: job.id, record_id: job.id}}
        %td.clickable.hidden-print{style: "background-color: ##{job.customer.area_color_cache}"}
          &nbsp;
        %td.clickable
          = job.formatted_time
        %td
          = job.invoice_number
        - job.customer.tap do |customer|
          - color_added = false
          - index_detail_values = customer.index_detail_values_from_cache(@work_list_default_customer_details_names)
          - @work_list_default_customer_details_names.count.times do |i|
            %td.clickable{style: !color_added && customer.color.present? ? "background-color:##{customer.color}" : ''}
              - color_added = true
              = index_detail_values[i]
        %td
          = render 'work_lists/editable_price_excluding_vat_td', job: job, default_vat_rate: default_vat_rate
        %td.clickable
          %span{style: 'margin-right: -4px'} &pound;
          %span.price-vat
            = job.vat(true, default_vat_rate)
        %td
          = render 'work_lists/editable_price_including_vat_td', job: job, default_vat_rate: default_vat_rate
        %td.clickable.hidden-print
          %span{style: 'margin-right: -4px'} &pound;
          %span.customer-outstanding-money
            = job.customer.outstanding_money
        %td.job-completed.hidden-print
          - if job.completed?
            = image_tag('tick.png')
          - else
            = link_to "Mark as completed", mark_as_completed_job_path(job), class: "btn btn-small", remote: true
        %td.job-paid
          %span.hidden-print
            - if job.paid?
              = job.total_payment_amount.format
              \-
              = job.total_payment_method.titleize
            - else
              = link_to "Mark as paid", '#', class: "mark-as-paid btn btn-small"
              .modal.job-paid-form.hide
                .modal-body
                  = form_for job, url: mark_as_paid_job_path(job), method: :put, remote: true do |f| 
                    %div
                      = label_tag 'job[payment_method]', 'Payment method'
                      = select_tag 'job[payment_method]', options_for_select(payment_methods_options)
                    %div
                      = label_tag 'job[payment_amount]', "Amount paid"
                      = text_field_tag 'job[payment_amount]', job.price
                    %div
                      = f.label :invoice_number
                      = f.text_field :invoice_number
                    %br
                    = f.submit "Mark as paid", class: 'btn btn-small'
                    = image_tag "ajax-loader.gif", class: "hide ajax-loader"
        %td.job-notes
          %span.hidden-print
            = link_to (job.job_notes.present? ? "Edit notes" : "Add notes"), '#', class: 'edit-notes'
            .modal.job-notes-form.hide
              .modal-body
                = render 'jobs/notes_form', job: job

        %td.hidden-print
          = link_to "Edit job", edit_job_path(job)
      - if job.job_notes.present?
        %tr.work-list-job-notes{class: odd_row && 'odd', id: "job-#{job.id}-notes", data:{job_id: job.id}}
          %td &nbsp;
          = render 'work_lists/job_notes_td', job: job
    %tr
      %th{colspan: @work_list_default_customer_details_names.length + 5, style: 'text-align:right'}
        Total
      %td= work_list.job_total_price_including_vat.format
      %td.hidden-print= work_list.job_total_outstanding_including_vat.format
      %td.hidden-print
        %strong= work_list.completed_job_total_price_including_vat.format
      %td.hidden-print= work_list.paid_job_total_price_including_vat.format
      %td.hidden-print &nbsp;
      %td{colspan: 2}

app/views/work_lists/add_job_for_customer.js.erb
(function() {
  <% if @success %>
    <% if params[:edit_after_save] %>
      window.location = "<%= edit_job_path(@job) %>";
    <% else %>
      $('tr[data-customer-id="<%= @customer.id %>"]').remove();
    <% end %>
  <% end %>
})();

app/views/work_lists/show.html.haml
:css
  @media print{@page {size: landscape}}
-$day_today = @work_list.date

.hidden-print
  - if current_user && (current_user.admin? || current_user.super_admin?)
    = link_to "Back to week", @work_list.week, class: 'btn'
  %br
  - if business_signed_in?
    - if current_user && (current_user.admin? || current_user.super_admin?)
      Public link:
      = link_to(url = work_list_url(@work_list, @work_list.url_token_params), url, target: '_blank')
  %br
  = link_to "Print", '#', onclick: 'window.print();'
  - if current_user && (current_user.admin? || current_user.super_admin?)
    - if business_signed_in?
      %br
      %span
        = link_to "Add job for new customer", quick_new_job_path(date: @work_list.date, work_list_category_id: @work_list.work_list_category_id), class: 'btn'
      %span
        = form_tag customer_search_work_list_path(@work_list), remote: true, id: "work-list-customer-search-form" do
          = text_field_tag :search_term, nil, placeholder: "Add job for existing customer"
          = submit_tag 'Search', class: 'btn', disabled: 'disabled'
      %span#work-list-ordering-enabler
        = link_to "Edit ordering", '#', class: "btn"
      %span#work-list-ordering-buttons.hide
        = link_to "Reset ordering", reset_job_ordering_work_list_path(@work_list), class: "btn"
        = link_to "Save ordering", update_job_ordering_work_list_path(@work_list), class: "btn save-ordering", data: {table_selector: 'table.work-list-table.ui-sortable', work_list_order: true}

= render 'show', work_list: @work_list, use_checkboxes: true

%div
  - unless @work_list.apply_target?
    Target is applied when there are jobs
  %div{class: @work_list.apply_target? || 'inactive-work-list-target'}
    - if current_user && (current_user.admin? || current_user.super_admin? || current_user.team_leader?)
      %h3 Target: #{@work_list.target.format}
      - if current_user && (current_user.admin? || current_user.super_admin?)
        - if business_signed_in?
          = form_for @work_list, url: update_target_work_list_path(@work_list) do |f|
            = f.label :target, "Set new target"
            = f.text_field :target
            %br
            = f.check_box :visible
            Visible
            %br
            = f.label :publication_date
            = f.date_field :publication_date
            = f.label :publication_time
            = f.time_field :publication_time
            %br
            %h5 Cleaners for this work list
            = f.collection_check_boxes :user_ids, current_business.users.where(role: 'Cleaner'), :id, :name do |b|
              = b.label class: "check-box" do
                = b.check_box class: "check-box"
                = b.object.name
            = f.submit "Submit", class: 'btn'

- day_options = short_days_of_week.map.with_index { |day, i| [day, i] }
- work_list_category_options = @work_list.week.work_lists.map(&:work_list_category).uniq.map { |wlc| [wlc.name, wlc.id] }
- if current_user && (current_user.admin? || current_user.super_admin?)
  - if business_signed_in?
    #move-selected-jobs-to-work-list.hidden-print
      /= select_tag :day, options_for_select([['N/A', -1]] + day_options, @work_list.day), {style: 'width: 80px'}
      = date_field_tag :date, @work_list.date
      = select_tag :work_list_category_id, options_for_select([['None', nil]] + work_list_category_options, @work_list.work_list_category_id), {style: 'width: 150px'}
      = link_to "Move selected jobs to this work list", '#', class: 'btn'
      = link_to "Cancel jobs", '#', class: "btn job-cancel-button"
    .hidden-print
      - if @work_list.completed?
        %h3 Work list signed off
        = link_to "Undo sign off", mark_as_incompleted_work_list_path(@work_list), class: 'btn'
      - else
        = link_to "Sign off work list", mark_as_completed_work_list_path(@work_list), class: 'btn'



.hidden-print
  .span6
    %h3 Notes
    - if @work_list.work_list_notes.length.zero?
      %span.no-work-list-notes No notes to show
    - else
      = render 'work_list_notes/table'
    = form_for [@work_list, WorkListNote.new], remote: true do |f|
      = hidden_field_tag :t1, @work_list.token_1
      = hidden_field_tag :t2, @work_list.token_2
      .work-list-note-errors.hide
      = f.label :content, "Add note"
      = f.text_area :content, size: "30x8"
      = f.submit "Submit", class: 'btn'

#customer-search-results.modal.hide.hidden-print
  .modal-body

:javascript
  $('form#work-list-customer-search-form input[name="search_term"]').on('keyup', function() {
    var self = $(this);
    var submitButton = self.siblings('input[type="submit"]');
    if (self.val() && self.val().length >= 3) {
      submitButton.removeAttr('disabled');
    } else {
      submitButton.attr('disabled', 'disabled');
    }
  });

app/views/work_lists/view.js.erb
window.location = '<%= j work_list_path(@work_list) %>';